/**
 * Generates a unique, 8-character alphanumeric string to serve as a match ID.
 * Example: 'ABC123XY'
 * 
 * @returns {string} The generated match ID
 */
export const generateMatchId = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 8; i++) {
    const randomIndex = Math.floor(Math.random() * chars.length);
    result += chars[randomIndex];
  }
  return result;
};

/**
 * Creates a shareable relative URL link for a given match ID.
 * 
 * @param {string} id - The match ID (e.g. generated by generateMatchId)
 * @returns {string} The relative link for the match (e.g. '/match/ABC123XY')
 */
export const createMatchLink = (id) => {
  return `/match/${id}`;
};
